apiVersion: v1
kind: ConfigMap
metadata:
  name: document-processor-config
data:
  S3_BUCKET_NAME: prod-document-processor-data
  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/825982271549/prod-document-processor
  LOG_LEVEL: info
  FEATURE_FLAGS: "ingest_v2=true,priority_processing=true"
